### ISSUE TITLE
Problems with the SE Sinatra Quiz

### ISSUE THREAD

**Issue by joedietrich-dev** [learn-co-curriculum/phase-3-quiz-sinatra#2]
### Canvas Link

https://learning.flatironschool.com/courses/3539/quizzes/22791/take/questions/148928

### Concern

Questions 3 and 7 have issues that prevent correct scoring, or which are clearly errors. See the attached for the issue with Question 3. Question 7 has two drop-down selectors, both of which only allow a single choice. When submitted, Question 7 gave 67% partial credit, even though there are only two questions and both were answered correctly (with the only two options provided).
![question3](https://user-images.githubusercontent.com/84293052/143789798-c4a9517a-bac4-40c9-bcfc-653fefb463e8.png)

**Comment by ihollander** [comment]
Hi @joedietrich-dev - thanks for flagging this issue! The quiz has been updated so that these questions function as intended.
