### ISSUE TITLE
Broken Fill-in-the-Blank Questions on Sinatra Quiz

### ISSUE THREAD

**Issue by dbagley1** [learn-co-curriculum/phase-3-quiz-sinatra#4]
### Canvas Link

https://my.learn.co/courses/358/quizzes/2068

### Concern

Two questions are meant to be fill in the blanks, but the blanks don't appear making it impossible to answer. The links "part1", "part2", and "option1" lead to a 404 page.

![image](https://user-images.githubusercontent.com/59030213/174453241-1d488637-db8c-4738-a1db-81f7fd2ce870.png)
![image](https://user-images.githubusercontent.com/59030213/174453251-f35f82b8-5bb9-4d66-be3f-a39611f9f63a.png)

**Comment by lizbur10** [comment]
Hi @dbagley1 ! Thanks for bringing this to our attention. Those questions should now be fixed, but please let us know if there are any remaining issues.

Thanks for contributing! 💙
