### ISSUE TITLE
Question 7 can't be answered as it has no input field

### ISSUE THREAD

**Issue by Said-cmd** [learn-co-curriculum/phase-3-quiz-sinatra#5]
<img width="888" alt="Screenshot 2022-09-01 at 12 26 38" src="https://user-images.githubusercontent.com/60461223/187881154-e4211d72-6052-4589-a4cb-cc4236570d51.png">

**Comment by lizbur10** [comment]
Hi @Said-cmd ! It appears as if this has been fixed - the question is displaying properly in the quiz blueprint - so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron School curriculum 💙
