### ISSUE TITLE
No answer field or options displayed for Question 7

### ISSUE THREAD

**Issue by nelsonmutindamwanzia** [learn-co-curriculum/phase-3-quiz-sinatra#6]
The question cannot be answered because either the options are missing or the input fields are not being displayed.

**Comment by lizbur10** [comment]
Hi @nelsonmutindamwanzia ! It appears as if this has been fixed - the question is displaying properly in the quiz blueprint - so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron School curriculum 💙
